#!/usr/bin/env python3
# Pre-compress immutable JS/CSS assets at build time.
#
# ASSETS = single-symbol assets. The R"DELIM(...)DELIM" body of the named
# PROGMEM symbol is extracted, gzipped, emitted as <SYM>.gz.h with:
#   static const uint8_t SYM_GZ[] PROGMEM = { ... };
#   static const size_t  SYM_GZ_LEN = ...;
#   #define EG_GZ_<SYM> 1
#
# ASSETS_COMBINED = multi-source bundles. Source bodies are concatenated
# in list order, then gzipped as a single stream (browsers don't reliably
# handle RFC 1952 multi-member gzip; one stream is mandatory).
#
# Per-asset fallback: any failure writes the header with EG_GZ_<NAME> 0.
# Consumers then fall through to the raw R"..." path. Whole build never
# fails because of this script.

import gzip
import io
import os
import re
import sys

ASSETS = [
    ("ESPGeiger/src/NTP/NTP.cpp",             "NTP_PAGE_JS", "application/javascript"),
    ("ESPGeiger/src/WebPortal/WebPortal.cpp", "STYLE_CSS",   "text/css"),
    ("ESPGeiger/src/WebPortal/WebPortal.cpp", "THEME_JS",    "application/javascript"),
]

ASSETS_COMBINED = [
    ("JS_BUNDLE", [
        ("ESPGeiger/src/WebPortal/WebPortal.cpp", "picographJS"),
        ("ESPGeiger/src/WebPortal/WebPortal.cpp", "statusJS"),
    ], "application/javascript"),
    ("HVJS_BUNDLE", [
        ("ESPGeiger/src/WebPortal/WebPortal.cpp", "picographJS"),
        ("ESPGeiger/src/HV/HV.cpp",               "hvJS"),
    ], "application/javascript"),
]

# [extern|static] const char NAME[] PROGMEM = R"DELIM( ... )DELIM";
RAW_RE_TMPL = (
    r'(?:extern|static)\s+const\s+char\s+{name}\s*\[\s*\]\s*PROGMEM\s*=\s*'
    r'R"([A-Za-z0-9_]+)\((.*?)\)\1"\s*;'
)


def extract_raw(src_path, sym):
    with open(src_path, "r", encoding="utf-8") as f:
        text = f.read()
    m = re.search(RAW_RE_TMPL.format(name=re.escape(sym)), text, re.DOTALL)
    if not m:
        return None
    return m.group(2).encode("utf-8")


def gzip_bytes(payload):
    buf = io.BytesIO()
    with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9, mtime=0) as gz:
        gz.write(payload)
    return buf.getvalue()


def emit_header(out_path, name, ok, blob=None, raw_len=0):
    lines = []
    lines.append("// Generated by scripts/gzip_assets.py - do not edit.")
    lines.append(f"// Source: {name}")
    if ok:
        lines.append(f"// Raw {raw_len} B -> gzip {len(blob)} B "
                     f"({100 * len(blob) // raw_len if raw_len else 0}%)")
        lines.append("")
        lines.append(f"#define EG_GZ_{name} 1")
        lines.append(f"static const size_t {name}_GZ_LEN = {len(blob)};")
        lines.append(f"static const uint8_t {name}_GZ[] PROGMEM = {{")
        for i in range(0, len(blob), 16):
            chunk = blob[i:i + 16]
            lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
        lines.append("};")
    else:
        lines.append(f"#define EG_GZ_{name} 0")
    lines.append("")
    new_text = "\n".join(lines)

    if os.path.exists(out_path):
        with open(out_path, "r", encoding="utf-8") as f:
            if f.read() == new_text:
                return
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(new_text)


def process_single(project_dir, gen_dir, rel_path, sym):
    out_path = os.path.join(gen_dir, f"{sym}.gz.h")
    try:
        raw = extract_raw(os.path.join(project_dir, rel_path), sym)
        if raw is None:
            print(f"[gzip_assets] {sym}: extract miss in {rel_path}; raw fallback")
            emit_header(out_path, sym, ok=False)
            return 0, 0
        blob = gzip_bytes(raw)
        emit_header(out_path, sym, ok=True, blob=blob, raw_len=len(raw))
        print(f"[gzip_assets] {sym}: {len(raw)} -> {len(blob)} B "
              f"({100 * len(blob) // len(raw)}%)")
        return len(raw), len(blob)
    except Exception as e:
        print(f"[gzip_assets] {sym}: {e}; raw fallback")
        emit_header(out_path, sym, ok=False)
        return 0, 0


def process_combined(project_dir, gen_dir, name, parts):
    out_path = os.path.join(gen_dir, f"{name}.gz.h")
    try:
        chunks = []
        for rel_path, sym in parts:
            raw = extract_raw(os.path.join(project_dir, rel_path), sym)
            if raw is None:
                print(f"[gzip_assets] {name}: extract miss for {sym} in "
                      f"{rel_path}; raw fallback")
                emit_header(out_path, name, ok=False)
                return 0, 0
            chunks.append(raw)
        raw = b"".join(chunks)
        blob = gzip_bytes(raw)
        emit_header(out_path, name, ok=True, blob=blob, raw_len=len(raw))
        print(f"[gzip_assets] {name} ({'+'.join(s for _, s in parts)}): "
              f"{len(raw)} -> {len(blob)} B ({100 * len(blob) // len(raw)}%)")
        return len(raw), len(blob)
    except Exception as e:
        print(f"[gzip_assets] {name}: {e}; raw fallback")
        emit_header(out_path, name, ok=False)
        return 0, 0


def run(project_dir, gen_dir):
    os.makedirs(gen_dir, exist_ok=True)
    total_raw = 0
    total_gz = 0
    for rel_path, sym, _ct in ASSETS:
        r, g = process_single(project_dir, gen_dir, rel_path, sym)
        total_raw += r
        total_gz += g
    for name, parts, _ct in ASSETS_COMBINED:
        r, g = process_combined(project_dir, gen_dir, name, parts)
        total_raw += r
        total_gz += g
    if total_raw:
        print(f"[gzip_assets] total {total_raw} -> {total_gz} B "
              f"(saved {total_raw - total_gz} B)")


# PIO entry point: pre-script invoked from platformio.ini.
try:
    Import("env")  # type: ignore  # noqa: F821
    _project_dir = env["PROJECT_DIR"]  # type: ignore  # noqa: F821
    _build_dir = env.subst("$BUILD_DIR")  # type: ignore  # noqa: F821
    _gen_dir = os.path.join(_build_dir, "generated")
    run(_project_dir, _gen_dir)
    env.Append(CPPPATH=[_gen_dir])  # type: ignore  # noqa: F821
except NameError:
    if __name__ == "__main__":
        # CLI fallback: python scripts/gzip_assets.py <gen_dir>
        gen = sys.argv[1] if len(sys.argv) > 1 else "build_test/generated"
        run(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), gen)
