#!/usr/bin/env python3
# Pre-compress immutable JS/CSS assets at build time.
#
# ASSETS = single-symbol assets. The R"DELIM(...)DELIM" body of the named
# PROGMEM symbol is extracted, gzipped, emitted as <SYM>.gz.h with:
#   static const uint8_t SYM_GZ[] PROGMEM = { ... };
#   static const size_t  SYM_GZ_LEN = ...;
#   #define EG_GZ_<SYM> 1
#
# ASSETS_COMBINED = multi-source bundles. Source bodies are concatenated
# in list order, then gzipped as a single stream (browsers don't reliably
# handle RFC 1952 multi-member gzip; one stream is mandatory).
#
# Per-asset fallback: an unexpected failure writes the header with
# EG_GZ_<NAME> 0 and consumers fall through to the raw R"..." path, so a
# surprise here never breaks the build.
#
# A missing file or symbol is different: the table above is stale and the
# asset ships uncompressed forever with nobody looking. That is a build
# error. HIST_JS sat unnoticed that way from b026bb7d until 2026-09-25.
# Set EG_GZ_ALLOW_STALE=1 to downgrade it to the raw fallback.

import gzip
import io
import os
import re
import sys

ASSETS = [
    ("ESPGeiger/src/NTP/NTP.cpp",                 "NTP_PAGE_JS", "application/javascript"),
    ("ESPGeiger/src/WebPortal/WebPortal.cpp",     "STYLE_CSS",   "text/css"),
    ("ESPGeiger/src/WebPortal/WebPortal.cpp",     "THEME_JS",    "application/javascript"),
    ("ESPGeiger/src/Counter/CounterWeb.cpp",      "HIST_JS",     "application/javascript"),
    ("ESPGeiger/src/OLEDDisplay/OLEDDisplay.cpp", "screenJS",    "application/javascript"),
]

ASSETS_COMBINED = [
    ("JS_BUNDLE", [
        ("ESPGeiger/src/WebPortal/WebPortal.cpp", "picographJS"),
        ("ESPGeiger/src/WebPortal/WebPortal.cpp", "statusJS"),
    ], "application/javascript"),
    ("HVJS_BUNDLE", [
        ("ESPGeiger/src/WebPortal/WebPortal.cpp", "picographJS"),
        ("ESPGeiger/src/HV/HV.cpp",               "hvJS"),
    ], "application/javascript"),
]

# [extern|static] const char NAME[] PROGMEM = R"DELIM( ... )DELIM";
RAW_RE_TMPL = (
    r'(?:extern|static)\s+const\s+char\s+{name}\s*\[\s*\]\s*PROGMEM\s*=\s*'
    r'R"([A-Za-z0-9_]+)\((.*?)\)\1"\s*;'
)


class StaleAsset(Exception):
    """A configured source file or symbol does not exist."""


ALLOW_STALE = os.environ.get("EG_GZ_ALLOW_STALE") == "1"


def extract_raw(src_path, rel_path, sym):
    if not os.path.isfile(src_path):
        raise StaleAsset(f"{sym}: no such file {rel_path}")
    with open(src_path, "r", encoding="utf-8") as f:
        text = f.read()
    m = re.search(RAW_RE_TMPL.format(name=re.escape(sym)), text, re.DOTALL)
    if not m:
        raise StaleAsset(f"{sym}: symbol not found in {rel_path}")
    return m.group(2).encode("utf-8")


def gzip_bytes(payload):
    buf = io.BytesIO()
    with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9, mtime=0) as gz:
        gz.write(payload)
    return buf.getvalue()


def emit_header(out_path, name, ok, blob=None, raw_len=0):
    lines = []
    lines.append("// Generated by scripts/gzip_assets.py - do not edit.")
    lines.append(f"// Source: {name}")
    if ok:
        lines.append(f"// Raw {raw_len} B -> gzip {len(blob)} B "
                     f"({100 * len(blob) // raw_len if raw_len else 0}%)")
        lines.append("")
        lines.append(f"#define EG_GZ_{name} 1")
        lines.append(f"static const size_t {name}_GZ_LEN = {len(blob)};")
        lines.append(f"static const uint8_t {name}_GZ[] PROGMEM = {{")
        for i in range(0, len(blob), 16):
            chunk = blob[i:i + 16]
            lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
        lines.append("};")
    else:
        lines.append(f"#define EG_GZ_{name} 0")
    lines.append("")
    new_text = "\n".join(lines)

    if os.path.exists(out_path):
        with open(out_path, "r", encoding="utf-8") as f:
            if f.read() == new_text:
                return
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(new_text)


def process_single(project_dir, gen_dir, rel_path, sym):
    out_path = os.path.join(gen_dir, f"{sym}.gz.h")
    try:
        raw = extract_raw(os.path.join(project_dir, rel_path), rel_path, sym)
        blob = gzip_bytes(raw)
        emit_header(out_path, sym, ok=True, blob=blob, raw_len=len(raw))
        print(f"[gzip_assets] {sym}: {len(raw)} -> {len(blob)} B "
              f"({100 * len(blob) // len(raw)}%)")
        return len(raw), len(blob)
    except StaleAsset:
        emit_header(out_path, sym, ok=False)
        raise
    except Exception as e:
        print(f"[gzip_assets] {sym}: {e}; raw fallback")
        emit_header(out_path, sym, ok=False)
        return 0, 0


def process_combined(project_dir, gen_dir, name, parts):
    out_path = os.path.join(gen_dir, f"{name}.gz.h")
    try:
        chunks = []
        for rel_path, sym in parts:
            chunks.append(extract_raw(
                os.path.join(project_dir, rel_path), rel_path, sym))
        raw = b"".join(chunks)
        blob = gzip_bytes(raw)
        emit_header(out_path, name, ok=True, blob=blob, raw_len=len(raw))
        print(f"[gzip_assets] {name} ({'+'.join(s for _, s in parts)}): "
              f"{len(raw)} -> {len(blob)} B ({100 * len(blob) // len(raw)}%)")
        return len(raw), len(blob)
    except StaleAsset:
        emit_header(out_path, name, ok=False)
        raise
    except Exception as e:
        print(f"[gzip_assets] {name}: {e}; raw fallback")
        emit_header(out_path, name, ok=False)
        return 0, 0


def run(project_dir, gen_dir):
    os.makedirs(gen_dir, exist_ok=True)
    total_raw = 0
    total_gz = 0
    stale = []

    def collect(fn, *a):
        nonlocal total_raw, total_gz
        try:
            r, g = fn(project_dir, gen_dir, *a)
        except StaleAsset as e:
            stale.append(str(e))
            return
        total_raw += r
        total_gz += g

    for rel_path, sym, _ct in ASSETS:
        collect(process_single, rel_path, sym)
    for name, parts, _ct in ASSETS_COMBINED:
        collect(process_combined, name, parts)
    if total_raw:
        print(f"[gzip_assets] total {total_raw} -> {total_gz} B "
              f"(saved {total_raw - total_gz} B)")

    if stale:
        for s in stale:
            print(f"[gzip_assets] STALE {s}")
        if ALLOW_STALE:
            print(f"[gzip_assets] {len(stale)} stale, allowed; raw fallback")
            return
        raise SystemExit(
            f"[gzip_assets] {len(stale)} stale asset(s): the table in "
            f"{os.path.basename(__file__)} no longer matches the tree. Fix "
            f"the path/symbol, or set EG_GZ_ALLOW_STALE=1 to ship raw.")


# PIO entry point: pre-script invoked from platformio.ini.
try:
    Import("env")  # type: ignore  # noqa: F821
    _project_dir = env["PROJECT_DIR"]  # type: ignore  # noqa: F821
    _build_dir = env.subst("$BUILD_DIR")  # type: ignore  # noqa: F821
    _gen_dir = os.path.join(_build_dir, "generated")
    run(_project_dir, _gen_dir)
    env.Append(CPPPATH=[_gen_dir])  # type: ignore  # noqa: F821
except NameError:
    if __name__ == "__main__":
        # CLI fallback: python scripts/gzip_assets.py <gen_dir>
        gen = sys.argv[1] if len(sys.argv) > 1 else "build_test/generated"
        run(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), gen)
