name: Build

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        environments:
          - "esp32_cajoe_iotgm"
          - "esp32_cajoe_iotgm_no_pcnt"
          - "esp32_serial"
          - "esp32_testpulse"
          - "esp32_testpulseint"
          - "esp32oled_pulse"
          - "esp32oled_serial"
          - "esp8266_pulsemin"
          - "esp8266_serial"
          - "esp8266_test"
          - "esp8266_testpulse"
          - "esp8266_testpulseint"
          - "esp8266oled_pulse"
          - "esp8266oled_serial"
          - "espgeigerhw"
          - "espgeigerlite"
          - "espgeigerlog"
          - "espgeigerlog_testpulseint"
    runs-on: ubuntu-latest
    name: Build with PlatformIO
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install platformio
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Run PlatformIO
        run: platformio run -e ${{ matrix.environments }}
      - name: Upload Assets
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.environments }}
          path: |
            .pio/build/*/firmware.bin
            .pio/build/*/firmware_merged.bin
          retention-days: 7
